"""update body column to Text

Revision ID: 71adb1b07230
Revises: 708c37410adb
Create Date: 2024-09-10 14:51:11.862832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71adb1b07230'
down_revision = '708c37410adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=mysql.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=140),
               existing_nullable=False)

    # ### end Alembic commands ###
