"""new fields in user model

Revision ID: 93514f46aaa3
Revises: 2070d6118499
Create Date: 2024-06-24 18:34:11.024379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93514f46aaa3'
down_revision = '2070d6118499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
